export const cambodiaCities = [
  { value: 'Banteay Meanchey', label: 'Banteay Meanchey' },
  { value: 'Battambang', label: 'Battambang' },
  { value: 'Kampong Cham', label: 'Kampong Cham' },
  { value: 'Kampong Chhnang', label: 'Kampong Chhnang' },
  { value: 'Kampong Speu', label: 'Kampong Speu' },
  { value: 'Kampot', label: 'Kampot' },
  { value: 'Kompong Thom', label: 'Kompong Thom' },
  { value: 'Kandal', label: 'Kandal' },
  { value: 'Koh Kong', label: 'Koh Kong' },
  { value: 'Kratié', label: 'Kratié' },
  { value: 'Mondulkiri', label: 'Mondulkiri' },
  { value: 'Phnom Penh', label: 'Phnom Penh' },
  { value: 'Preah Vihear', label: 'Preah Vihear' },
  { value: 'Prey Veng', label: 'Prey Veng' },
  { value: 'Pursat', label: 'Pursat' },
  { value: 'Ratanakiri', label: 'Ratanakiri' },
  { value: 'Siem Reap', label: 'Siem Reap' },
  { value: 'Preah Sihanouk', label: 'Preah Sihanouk' },
  { value: 'Stung Treng', label: 'Stung Treng' },
  { value: 'Svay Rieng', label: 'Svay Rieng' },
  { value: 'Takéo', label: 'Takéo' },
  { value: 'Oddar Meanchey', label: 'Oddar Meanchey' },
  { value: 'Kep', label: 'Kep' },
  { value: 'Pailin', label: 'Pailin' },
  { value: 'Tboung Khmum', label: 'Tboung Khmum' }
];
