query Categories($commonType: CommonTypeType!) {
  categories(commonType: $commonType) {
    id
    name
    subCategories {
      id
      name
      productTypes {
        id
        name
      }
    }
  }
}
