name: Type Check

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  type-check:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.compare_versions_step.outputs.should_build }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3.5.2

      - name: Use Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Lint check
        run: yarn lint

      - name: Type check
        run: yarn tsc --noEmit
